export {default as Navbar} from './Navbar.jsx';
export {default as Hero} from './Hero.jsx';
export {default as Memory} from './Memory.jsx';
export {default as Explore} from './Explore.jsx';
export {default as Advertise} from './Advertise.jsx';
export {default as Pricing} from './Pricing.jsx';
export {default as Banner} from './Banner.jsx';
export {default as Newslatter} from './Newslatter.jsx';
export {default as Footer} from './Footer.jsx';
